language: java
addons:
  postgresql: "9.3"
before_install:
  - psql -c 'create database pg_hibernate;' -U postgres
  - psql -U pg_hibernate -c 'create extension hstore'
  - psql -U pg_hibernate -c 'GRANT ALL PRIVILEGES ON DATABASE pg_hibernate to postgres'
install:
  mvn verify
