language: java
addons:
  postgresql: "9.2"
before_script:
  - psql -c 'create database pg_hibernate;' -U postgres
  - psql -U postgres -c 'create extension hstore'
  - psql -U postgres -c 'CREATE USER postgres WITH PASSWORD \'\''
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE pg_hibernate to postgres';
install:
  mvn verify
